### ISSUE TITLE
"null" in feed data

### ISSUE THREAD

**Issue by kevquirk** [rknightuk/echo#2]
Hey Robb,

Loving this tool, it's great! I'm having a small issue where the feed I'm using (https://kevquirk.com/social-feed) is producing nothing but 'null' for the ID in the data folder, so it's dumping my entire feed every time the cron runs. This is 100% my fault, but I'm not sure what's happening here. What does echo use as the ID for posts? I can make sure it's added to the feed then.

For now, I've worked around the problem by simply limiting the feed to the single latest entry, so this is *really* low priority.

Thanks,

Kev

**Comment by kevquirk** [comment]
Never mind. I read the docs....need to add `guid` 🤦‍♂️

**Comment by kevquirk** [comment]
Ok, been digging into this a bit more, seems the `transform` is off in my config, so it's not picking up and ID for the posts. Don't know why though as I'm using the `default` transform which seems to look for generic parts of the feed, like post date  and content?

Here's my config:

```
export default {
  "services": {
    "masto": {
      "instance": "https://fosstodon.org",
      "accessToken": "<<REMOVED>>",
      "visibility": "direct",
      "sensitive": false
    }
  },
  "sites": [
    {
      "name": "social_feed",
      "feed": "https://kevquirk.com/social-feed",
      "json": false,
      "categories": [],
      "services": [
        "masto"
      ],
      "transform": presets.default
    }
  ]
}
```

**Comment by rknightuk** [comment]
Let me have a gander for you Kev and I'll come back to you

**Comment by kevquirk** [comment]
No rush, Robb, it's Christmas and I'm clearly being a muppet somewhere. :)

Thanks though, mate.

**Comment by rknightuk** [comment]
I did have a little moment when I saw all the posts come in thinking this might be related to Echo 🤣

**Comment by kevquirk** [comment]
Hahaha it's your own fault for writing about it in your 2024 post! :)

**Comment by kevquirk** [comment]
I did a `dry` run and the results were good, so I assume I'd be fine. Oh how wrong I could be haha.

```
$ node index.js dry
🌵 Running in dry mode, no posts will be created
⚙️ Fetching for social_feed
☑️ Will create social_feed post for 2023-12-22T19:45:00.000Z - 

        I love motorbikes, but back in October 2016 I had a head-on collision with a van, which I caught on video. Here's the story...

        https://kevquirk.com/that-time-i-crashed-my-motorbike
```

**Comment by rknightuk** [comment]
Got it, so the `presets.default` does `data.id` on the rss items but your feed uses `guid` so your config needs look like this instead to get the `guid` as the ID:

```diff
- "transform": presets.default,
+ "transform": {
+  getId: (data) => {
+    return data.guid
+  },
+  format: presets.default.format,
+ }
```

I'm going to update Echo so it warns if there's no ID match

**Comment by rknightuk** [comment]
Echo has been updated so it will error when this happens.

**Comment by kevquirk** [comment]
Thanks Robb. I seem to have broken my config file now. I'm getting the following error:

```
Current status: 1 (Interrupted)
Standard output/error:
file:///volume1/homes/kev/echo/config.js:29
]
^

SyntaxError: Unexpected token ']'
```

But if I remove "]" on line 29, it still doesn't work and I get another error. Clearly a syntax problem, but I don't know enough to fix it. :(

```
import helpers from './lib/helpers.js'
import presets from './lib/presets.js'
import { SERVICES } from './lib/posters/index.js'

export default {
  "services": {
    "masto": {
      "instance": "https://fosstodon.org",
      "accessToken": "<<REMOVED>>",
      "visibility": "direct",
      "sensitive": false
    }
  },
  "sites": [
    {
      "name": "social_feed",
      "feed": "https://kevquirk.com/social-feed",
      "json": false,
      "categories": [],
      "services": [
        "masto"
      ],
      "transform": {
        getId: (data) => {
            return data.guid
        },
       "format": presets.default.format,
      }
  ]
}
```

**Comment by rknightuk** [comment]
Missing a curly bracket, try this:

```js
import helpers from './lib/helpers.js'
import presets from './lib/presets.js'
import { SERVICES } from './lib/posters/index.js'

export default {
  "services": {
    "masto": {
      "instance": "https://fosstodon.org",
      "accessToken": "<<REMOVED>>",
      "visibility": "direct",
      "sensitive": false
    }
  },
  "sites": [
    {
      "name": "social_feed",
      "feed": "https://kevquirk.com/social-feed",
      "json": false,
      "categories": [],
      "services": [
        "masto"
      ],
      "transform": {
        getId: (data) => {
            return data.guid
        },
       "format": presets.default.format,
      }
    },
  ]
}
```

**Comment by kevquirk** [comment]
Ta daaaaaa! It works and I no longer see `null` in the data folder. Thanks, Robb!
